[versions]
## Hytale
hytale = "1.0.0" # https://hytale.com

## Paper
paperweight = "2.0.0-beta.19" # https://github.com/PaperMC/paperweight
run-paper = "3.0.2" # https://github.com/jpenilla/run-task
paper = "1.21.11-R0.1-SNAPSHOT" # https://github.com/PaperMC/Paper

velocity = "3.4.0-SNAPSHOT" # https://docs.papermc.io/velocity/dev/creating-your-first-plugin/

## Minecraft
minecraft = "1.21.11" # https://minecraft.net

## Kyori
adventure = "4.26.1" # https://github.com/KyoriPowered/adventure

## Other
fusion = "4.0.0-SNAPSHOT" # https://github.com/ryderbelserion/Fusion

## Gradle Plugins
fix-javadoc = "1.19" # https://github.com/mfnalex/gradle-fix-javadoc-plugin
curseforge = "1.1.26" # https://github.com/Darkhax/CurseForgeGradle
minotaur = "2.8.10" # https://github.com/modrinth/minotaur
feather = "0.4.0" # https://github.com/ryderbelserion/Feather
hangar = "0.1.4" # https://github.com/HangarMC/hangar-publish-plugin
shadow = "9.3.0" # https://github.com/GradleUp/shadow

## Databases
hikari = "7.0.2" # https://github.com/brettwooldridge/HikariCP
postgres = "42.7.8" # https://github.com/postgres/postgres

luckperms = "5.4" # https://github.com/LuckPerms/LuckPerms

# Commands
cloud-release = "2.0.0" # https://cloud.incendo.org/core/
cloud-beta = "2.0.0-beta.14" # https://cloud.incendo.org/minecraft/paper/

logback-classic = "1.5.20" # https://github.com/qos-ch/logback
jopt-simple = "5.0.4" # https://github.com/jopt-simple/jopt-simple
jda = "6.3.0" # https://github.com/discord-jda/JDA

[plugins]
# https://github.com/mfnalex/gradle-fix-javadoc-plugin
fix-javadoc = { id = "com.jeff-media.fix-javadoc-plugin", version.ref = "fix-javadoc" }

[libraries]
# https://github.com/Darkhax/CurseForgeGradle
curseforge = { group = "net.darkhax.curseforgegradle", name = "net.darkhax.curseforgegradle.gradle.plugin", version.ref = "curseforge" }

# https://github.com/PaperMC/paperweight
paperweight = { module = "io.papermc.paperweight.userdev:io.papermc.paperweight.userdev.gradle.plugin", version.ref = "paperweight" }

# https://github.com/ryderbelserion/Feather
feather = { module = "com.ryderbelserion.feather.core:com.ryderbelserion.feather.core.gradle.plugin", version.ref = "feather" }

# https://github.com/HangarMC/hangar-publish-plugin
hangar = { module = "io.papermc.hangar-publish-plugin:io.papermc.hangar-publish-plugin.gradle.plugin", version.ref = "hangar" }

# https://github.com/jpenilla/run-task
run-velocity = { module = "xyz.jpenilla.run-velocity:xyz.jpenilla.run-velocity.gradle.plugin", version.ref = "run-paper" }
# https://github.com/jpenilla/run-task
run-paper = { module = "xyz.jpenilla.run-paper:xyz.jpenilla.run-paper.gradle.plugin", version.ref = "run-paper" }

# https://github.com/modrinth/minotaur
minotaur = { module = "com.modrinth.minotaur:com.modrinth.minotaur.gradle.plugin", version.ref = "minotaur" }

# https://github.com/GradleUp/shadow
shadow = { module = "com.gradleup.shadow:shadow-gradle-plugin", version.ref = "shadow" }

# https://github.com/postgres/postgres
postgres = { module = "'org.postgresql:postgresql", version.ref = "postgres" }

# https://github.com/brettwooldridge/HikariCP
hikari-cp = { module = "com.zaxxer:HikariCP", version.ref = "hikari" }

# https://cloud.incendo.org/annotations/
cloud-annotations = { module = "org.incendo:cloud-annotations", version.ref = "cloud-release" }
# https://cloud.incendo.org/minecraft/minecraft-extras/
cloud-extras = { module = "org.incendo:cloud-minecraft-extras", version.ref = "cloud-beta" }
# https://cloud.incendo.org/core/
cloud-core = { module = "org.incendo:cloud-core", version.ref = "cloud-release" }
# https://cloud.incendo.org/minecraft/paper/
cloud-paper = { module = "org.incendo:cloud-paper", version.ref = "cloud-beta" }

# https://github.com/ryderbelserion/Fusion
fusion-paper = { module = "com.ryderbelserion.fusion:fusion-paper", version.ref = "fusion" }
fusion-files = { module = "com.ryderbelserion.fusion:fusion-files", version.ref = "fusion" }
fusion-kyori = { module = "com.ryderbelserion.fusion:fusion-kyori", version.ref = "fusion" }
fusion-core = { module = "com.ryderbelserion.fusion:fusion-kyori", version.ref = "fusion" }

# https://github.com/KyoriPowered/adventure
kyori-logger = { module = "net.kyori:adventure-text-logger-slf4j", version.ref = "adventure" }
kyori-text = { module = "net.kyori:adventure-text-minimessage", version.ref = "adventure" }
kyori-api = { module = "net.kyori:adventure-api", version.ref = "adventure" }

# https://docs.papermc.io/velocity/dev/creating-your-first-plugin/
velocity = { module = "com.velocitypowered:velocity-api", version.ref = "velocity" }

# https://github.com/LuckPerms/LuckPerms
luckperms = { module = "net.luckperms:api", version.ref = "luckperms" }

# https://github.com/qos-ch/logback
classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback-classic" }
# https://github.com/jopt-simple/jopt-simple
jopt = { module = "net.sf.jopt-simple:jopt-simple", version.ref = "jopt-simple" }
# https://github.com/discord-jda/JDA
jda = { module = "net.dv8tion:JDA", version.ref = "jda" }

[bundles]
cloud-paper = [
    "cloud-annotations",
    "cloud-extras",
    "cloud-paper"
]

kyori = [
    "kyori-logger",
    "kyori-text",
    "kyori-api"
]

build = [
    "curseforge",
    "minotaur",
    "feather",
    "hangar",
    "shadow"
]

paper = [
    "paperweight",

    "run-velocity",
    "run-paper"
]